version: '3.7'
services:

  yb-master:
    image: yugabytedb/yugabyte:2.16.1.1-b3
    container_name: yb-master-n1
    volumes:
      - ./mnt/yugabyte/yb-master-data-1:/mnt/master
    command:
      [
        "/home/yugabyte/bin/yb-master",
        "--fs_data_dirs=/mnt/master",
        "--master_addresses=yb-master-n1:7100",
        "--rpc_bind_addresses=yb-master-n1:7100",
        "--replication_factor=1"
      ]
    ports:
      - "7000:7000"
      - "7100:7100"
    environment:
      - SERVICE_7000_NAME=yb-master

  yb-tserver:
    image: yugabytedb/yugabyte:2.16.1.1-b3
    container_name: yb-tserver-n1
    depends_on:
      - yb-master
    volumes:
      - ./mnt/yugabyte/yb-tserver-data-1:/mnt/tserver
    command:
      [
        "/home/yugabyte/bin/yb-tserver",
        "--fs_data_dirs=/mnt/tserver",
        "--start_pgsql_proxy",
        "--rpc_bind_addresses=yb-tserver-n1:9100",
        "--tserver_master_addrs=yb-master-n1:7100"
      ]
    ports:
      - "9042:9042"
      - "5433:5433"
      - "9000:9000"
      - "13000:13000"
      - "11000:11000"
      - "12000:12000"
    environment:
      - SERVICE_5433_NAME=ysql
      - SERVICE_9042_NAME=ycql
      - SERVICE_6379_NAME=yedis
      - SERVICE_9000_NAME=yb-tserver


  prometheus:
    image: prom/prometheus:v2.29.2
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./mnt/prometheus/:/etc/prometheus/

  grafana:
    image: grafana/grafana:8.1.3
    container_name: grafana
    environment:
      - "GF_SECURITY_ADMIN_USER=admin"
      - "GF_SECURITY_ADMIN_PASSWORD=password"
      - "GF_USERS_ALLOW_SIGN_UP=false"
    ports:
      - 3000:3000
    volumes:
      - ./mnt/grafana/:/etc/grafana/provisioning


